### ISSUE TITLE
registro

### ISSUE THREAD

**Issue by pirataxxx** [rascii/risus2#1]
hola amigo descarge esta https://github.com/rascii/risus2/releases/tag/v1.0.2 y todo bien pero cuando intento registrar un nuevo usuario no pasa nada ademas q el registro es diferente al de aqui te dejo una captura de donde se queda atorado http://prntscr.com/mf184d la web es http://mexicopirata.x3host.ml/

**Comment by rascii** [comment]
Asegúrate de tener la versión correcta de Phpost Risus, al igual de que las tablas del recaptcha existan.

**Comment by Borea** [comment]
Aprovechando el topic pregunto: ¿Cuál es la versión correcta?

**Comment by rascii** [comment]
Probé el tema con la 1.3, ahora con la 1.2 desconozco que funcione aunque lo más probable es que sí.
